### ISSUE TITLE
Il notebook U-Net risulta mancante

### ISSUE THREAD

**Issue by marco-sarti** [SimoneTruglia/My-Journey-on-Artificial-Intelligence#1]
![image](https://github.com/SimoneTruglia/My-Journey-on-Artificial-Intelligence/assets/4919885/1aab97c7-8f28-419a-9454-1e1af83d097c)

**Comment by SimoneTruglia** [comment]
Che strano, l'ho caricato dal locale assieme a tutte gli altri file.

Avrà avuto qualche problema durante l'upload. L'ho ricaricato, grazie mille della segnalazione. Ora mi riguardo piano piano tutti gli altri perché se l'ha fatto su questo magari lo ha fatto anche qualche altro notebook :)

Queusto qui in particolare counque dovrebbe essere abbastanza simile a quello scaricabile dalla piattaforma, perché su questa esercitazione qui non mi pare che ho fatto troppi ragionamenti a lato, perché alla fine è un'architettura fatta così, da prendere e da usare, un po' come dicevi iera sera in call su alcune cose che si vedranno
